### ISSUE TITLE
settings make process crash

### ISSUE THREAD

**Issue by dabtapp** [iPzard/mkvtoolnix-batch-tool#13]
the extra settings make for a batch process to crash after processing first video file in a directory. 
After this it doesnt notice the directory anymore.

The 
![1](https://user-images.githubusercontent.com/77730949/105173970-18526200-5b22-11eb-8f6e-9de48cec1967.PNG)
![2](https://user-images.githubusercontent.com/77730949/105173972-18eaf880-5b22-11eb-89c0-6bc3b72b721b.PNG)

**Comment by iPzard** [comment]
Thanks for reporting this. It seems to be working as expected for me, can you include more information on this? For example, what directory structure you're processing looks like.. file names/types, etc..?

**Comment by dabtapp** [comment]
tried all, didnt work, other options work, just not this middle one, it seems to have issues removing video files from a directory. I do it straight from the c: downloads

**Comment by iPzard** [comment]
No, that wouldn't cause an error or anything. This info should help me get to the root cause, would you mind providing the following information?

1. Did you selected "allow" when being asked about network permissions for MKVToolNix Batch Tool?
2. Can you provide further information on the directory structure, including files (names/extensions)?
3. Are their nested sub-directories in `c:\downloads`? If so, can you provide the file data (names/extensions) for those too?

**Comment by dabtapp** [comment]
1: there was no prompt. It starts processing itself and then just errors out.
2. Directory structures? none. this is in downloads, where i simply made a random folder with a bunch of numbers you can see the filename in the source directory picture.
3. no subdirectories, it goes straight from the downloads map.

**Comment by iPzard** [comment]
Cool, thanks for the info.. So, it will always ask for network permission the very first time starting the app after install, after that it will remember your first selection. If you don't remember ever selecting an option here it's likely "allow" was not selected when prompted, in which case Windows selects "deny" for you by default.

I'd recommend uninstalling and reinstalling the app. Then when starting the app for the very first time after re-installing, be sure to "allow" network connections, otherwise this error will pop up whenever you try to process a batch.

**Comment by iPzard** [comment]
So when running the app as admin, you're able to process the batch?

**Comment by dabtapp** [comment]
i dont need to run anything or set any permission, i installed the app and ran it. It just runs.

**Comment by iPzard** [comment]
I understand that, but some folders require elevated permissions to delete items. If you're unwilling to attempt troubleshooting steps being offered then I'm not going to be able to help much.

**Comment by dabtapp** [comment]
there are no permission issues. I use the setting to remove items in regular mkvtoolnix aswell without issues.

**Comment by iPzard** [comment]
The regular MKVToolNix GUI does not have options to delete items after processing.

**Comment by dabtapp** [comment]
[](url)
![123](https://user-images.githubusercontent.com/77730949/105254827-b1b16080-5b82-11eb-9540-e216ec0ee05c.PNG)
wrong

**Comment by iPzard** [comment]
If you're just here to argue then I'm going to close the ticket. I'm not going to be able to help if you're not willing to attempt the troubleshooting steps being provided.
