### ISSUE TITLE
feature request: show completion percentage of individual files / overall job

### ISSUE THREAD

**Issue by sweaver2** [iPzard/mkvtoolnix-batch-tool#24]
it would be great to be able to see a percent progress on the individual files, as well as the overall batch job (similar to the mkvtoolnix ui)
![image](https://user-images.githubusercontent.com/42624300/111821706-31685c80-88a0-11eb-99c1-e53098a281c6.png)

**Comment by iPzard** [comment]
Great suggestion! I can look into this but not sure if this is possible using theMKVToolNix CLI interface options, which is what this program takes advantage of to make batching possible.

**Comment by seantcanavan** [comment]
@iPzard it's written in python but this author managed to get the process percentage from the CLI: https://github.com/willforde/mkvstrip/blob/master/mkvstrip.py#L131

**Comment by iPzard** [comment]
Wow, @seantcanavan thanks for this!! I guess Python may offer a workaround to gather this data, I looked at your link briefly and it seems promising. I will take a closer look when I'm working through this ticket and determine its feasibility. I'll update here too as things progress.

**Comment by seantcanavan** [comment]
@iPzard no problem! If I may selfishly mention I'm currently working on improving the following workflow:

1. Use MKVStrip to remove all non-english subtitles and audio tracks from MKV files
2. Use Subtitle Edit to convert all non-SRT subtitle formats to SRT (output in the starting directory)
3. Use your program to batch merge the SRT files back into the MKV

If you know of any way to do this process easier than utilizing 3 tools that would be amazing. But I found your tool from stackoverflow to do part 3 so at least the loop is closed now. It just seems that there's a lot of ways to do parts 1, 2, and 3 but no unified solution to do all of them in an automated CRON fashion so a media collection can be kept pruned and compatible across multiple platforms. I'm hard of hearing and I have a lot of issues with non-SRT subtitles depending on 4K TV make and model which is why I need to convert them all to SRT.

**Comment by iPzard** [comment]
I can probably help with #2, to an extent.. Currently, I force subtitles to UTF-8 for compatibility issues, this allows the tool to merge subtitles that even the underlining MKVToolNix can't do natively. 

I could potentially take that a step further and if the subtitle is an unsupported subtitle file extension, convert it to SRT. If that sounds good I can create a separate ticket to track and work on that feature.

**Comment by seantcanavan** [comment]
Alternatively if you want to spend a little time on updating the README on how to run the code I could try to contribute as well.

**Comment by iPzard** [comment]
Sounds good. Should be the same instructions, I would just try to automatically resolve incompatible subtitle files on the backend. Or was there something the README is currently lacking?

**Comment by iPzard** [comment]
@seantcanavan FYI..
https://github.com/iPzard/mkvtoolnix-batch-tool/issues/27

**Comment by iPzard** [comment]
Reviewing the open tickets this weekend.. After giving this one some thought, I think I'm gonna leave out the additional progress indicator. Here are the main reasons I came to that conclusion.

1. There's already an overall status indicator, having one also for individual file progress might be confusing.
2. Adding this feature awkward to implement in the UI alongside the other progress indicator.
4. Adding new packages to manage this will increase the overall bundle (program) size. 
3. The risk/reward for implementing this feature doesn't seem to be balanced well (high risk, low reward).
