### ISSUE TITLE
German Umlaute äöü outputs cryptic texts. Works with manual import to MKVtoolnix

### ISSUE THREAD

**Issue by tebo1000** [iPzard/mkvtoolnix-batch-tool#43]
**🦟 Describe the bug**
German Umlaute äöü outputs cryptic texts.
Works with manual import to MKVtoolnix.

**Steps to Reproduce**
The tool works without an error message, but when opening the output file, the subtitle text does not show the correct symbols for the German Umlaute äöü letter.
Works with manual import to MKVtoolnix of the very same files.

**Comment by iPzard** [comment]
They seem to be coming through for me when testing..
![umlaute](https://user-images.githubusercontent.com/8584126/139596313-ef5c2254-5c69-4f98-8aae-0aa425c0cc6e.png)

Are you using the [latest version](https://github.com/iPzard/mkvtoolnix-batch-tool/releases) of the software? If so, would you mind sharing the subtitle file so I can take a closer look?

**Comment by tebo1000** [comment]
Hm, that looks ok. Is there something I could have set up the wrong way?
Just downloaded the latest version of your tool and MKVToolNix and tried it again but with the same cryptic result.
![Sample 1](https://user-images.githubusercontent.com/93089949/139747747-a48805ce-7e08-4106-90fa-453cedd7ab2c.JPG)

[13_German.txt](https://github.com/iPzard/mkvtoolnix-batch-tool/files/7456381/13_German.txt)

I attached the srt file with txt extension. Srt is not supported for uploads.

**Comment by iPzard** [comment]
Looks like the program was trying to convert subtitles using an `ISO-8859-9` encoding method to `utf-8`, creating these text artifacts when attempting to convert German umlaut letters. 

Since there's no need to re-encode `ISO-8859-9` subtitle files, I've added `ISO-8859-9` to the encoding whitelist, which prevents re-encoding, in this commit https://github.com/iPzard/mkvtoolnix-batch-tool/commit/ee5b5c830e98b4d435b4210fcea3fb5c30d660f3.

I created a new release which patches this issue, you can find and download it from here:
[Release v2.2.5](https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v2.2.5)

Thanks for providing the test subtitle file, and for submitting this issue in the first place. These sort of issues are not always easy to detect, and this sort of help goes a long way in shaping a smooth experience in the end product.

**Comment by thehappysloth** [comment]
Hi, the problem is still occuring.  I'm trying to process french subtitles encoded in UTF-8 (according to Notepad++) and even if I uncheck "Remove known advertisements", my subtitle files are still rewritten with wrongs characters.  I wonder if the problem could be that you use "utf8" instead of "utf-8" in your ensure_utf8_encoding and remove_subtitles_ads functions.

I've attached before/after subtitles files :

[before.txt](https://github.com/iPzard/mkvtoolnix-batch-tool/files/7877656/before.txt)
[after.txt](https://github.com/iPzard/mkvtoolnix-batch-tool/files/7877657/after.txt)

Could you check if you manage to reproduce the problem?

Thanks!

**Comment by iPzard** [comment]
Thanks for bringing this up! I was able to reproduce the issue and create a new [release](https://github.com/iPzard/mkvtoolnix-batch-tool/releases) with this patched. VS Code was also saying `utf-8`, but looks like `chardet` was interpreting it as `Windows-1252` in the program. I've added that to the `encoding_method_whitelist` list which seems to have resolved the issues.

**Comment by iPzard** [comment]
Sweet, thanks for confirming! Glad to hear!
