### ISSUE TITLE
Support for idx/sub subtitles

### ISSUE THREAD

**Issue by reaseno** [iPzard/mkvtoolnix-batch-tool#50]
Could you please support idx/sub subtitles as well. This is now the majority of the subtitles I would like to integrate into videos. Especially since there are two files per language.

**Request details:**
- Update tool to support idx & sub subtitle file extensions.
- Update readme to show these extensions in the supported subtitle file extension section.

**Comment by iPzard** [comment]
Appreciate the enhancement request @reaseno! Will see what I can do about this. Currently, [`.smi` files are converted to `.srt`](https://github.com/iPzard/mkvtoolnix-batch-tool/blob/d8a45e6f1a5c6e3004eedfe04dcd445b920b7010/resources/modules/mkvtoolnix.py#L57) on the fly, I'm wondering if I can just add `.idx` to that list. Will look into this more and update here though.

**Comment by iPzard** [comment]
Having some trouble finding `.idx` & `.sub` files online to test with, will keep looking but would you mind uploading the one (of each if possible) that you're having trouble with and I can use that?

**Comment by reaseno** [comment]
https://we.tl/t-YLrTQXfuzV

runs for a week
Thank you :)

**Comment by iPzard** [comment]
Thanks for the link! Are you sure these are valid `sub` and `idx` files though? They don't seem to be recognized by VobSub, ffmpeg, or VLC. I even tried opening them with programs like Subtitle Creator but it says the files aren't valid.

**Comment by reaseno** [comment]
This is strange, since it is the most commonly used type along with .srt. It is the standard for bitmap subtitles and is used on all DVDs and Blu-rays. At least it is the subtitle format that tools export from DVD and Blu-Ray.

I downloaded the subtitle again and I can play it in vlc as well. The idx/sub is one subtitle and the files must have the same filename as the video. The MKVToolNix GUI also recognizes them, as well as the language, because it is included in the header of the idx file, which contains the metadata where the images are included in the .sub file.

**Comment by iPzard** [comment]
Strange.. I'm guessing it might be some environmental thing on my end.

I've added `idx` and `sub` to the list in this pre-release build, would you mind giving it a try? If it works for you I can publish it as a new release production release. 
[v2.2.8 pre-release](https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v2.2.8)

**Comment by iPzard** [comment]
You know what.. I just realized the idx and sub-files are processed together, I was trying them individually. I appreciate the insight and example files on this one!

I updated the subtitle extension whitelist as recommended and also updated the underlining `mkvmerge.exe` used internally by the tool to the latest version and that seems to have done the trick. There was no need to convert to `srt` or anything like that, just like you mentioned, it's already supported.

Had to play around with the language detection feature to parse the config data instead of reading the file, since it's always all English and there is no actual subtitle text in the file to parse.  

We should have full support for `idx` and `sub` files now in the v2.3.0 which you can now find in the [release](https://github.com/iPzard/mkvtoolnix-batch-tool/releases) section, feel to reopen this issue if you continue to run into any problems.
