### ISSUE TITLE
Update "Default language track" dropdown to include all supported languages

### ISSUE THREAD

**Issue by jartas** [iPzard/mkvtoolnix-batch-tool#6]
Please add support for set CZE language subtitles

**Comment by iPzard** [comment]
Thanks for reporting this.. Looks like MKVToolNix at its root does support CZE so I can add it, it also supports about 70 other languages I don't currently have in the default language track list. When originally piecing this software together the list of supported languages was so long I only added about 11 of the most popular languages. You can still add subtitles of other languages, it's just they won't be set as the default track.. but I know, that's probably what you want.

Since some people, such as yourself, are interested in setting the other languages as their default, I'll go in and add the rest to the list - which will be very long when I'm done, but shouldn't take too long to add.

**Comment by jartas** [comment]
Perfect thank you

**Comment by iPzard** [comment]
Ok, updated in version 1.1.1 (just released), includes Czech/CZE:
https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v1.1.1
![czech](https://user-images.githubusercontent.com/8584126/97809940-2c727b80-1c25-11eb-9c05-fad3ae097a1f.png)


Luckily, was able to find the full list of languages MKVToolNix supports:
https://gitlab.com/mbunkus/mkvtoolnix/-/blob/main/src/common/iso639_language_list.cpp
