### ISSUE TITLE
Support one folder 

### ISSUE THREAD

**Issue by jartas** [iPzard/mkvtoolnix-batch-tool#7]
Please support only one folder for serials. I have more files in one folder, for example S01E01.mkv ,S02E02.mkv atd... S01E01.srt, S01E02.srt atd.... now i Cannot add subtitles this folder. When I have 20 files i would create 20 folder. Thank you

**Comment by iPzard** [comment]
I can see the benefit of using this tool with a TV series, such as a "season 01" folder with 10 videos w/matching subtitles. I'll look into getting this added. It's a somewhat large change though, mostly because it contradicts with the way the current code works in a few ways, for example, it currently just looks for subdirectories. But the main reason this functionality was left out was because there's no way to know which subtitles are for which videos. 

My thoughts are the program can just check the current directory too, and then in the event of more than one video file being found in a directory, subtitles would be matched with their videos based on a naming convention; such as the subtitle file(s) must contain the full name of the video file it's for, within its own file name. As a side effect, non-matching files would be ignored.

I think it makes sense to have this one the roadmap.. but like I said, it's a somewhat large change compared to how things are now. So might take a little while to get around it.

**Comment by iPzard** [comment]
@jartas this has now been implemented, starting in release v2.0.0, thanks again for your feedback!
https://github.com/iPzard/mkvtoolnix-batch-tool/releases
