### ISSUE TITLE
Preserve Original Date Created

### ISSUE THREAD

**Issue by harmlessdonkey** [iPzard/mkvtoolnix-batch-tool#81]
Hi, 

Great tool. Really appreciate the work gone into it. I'd love an option for the original video files' created date to be carried over to the new MKV. I use the application to add the SRT file created by my drone with all the camera metadata (ISO, shutter speed, GPS data) and include it with the video file in an MKV so I don't have two files to manage. However, the new file has a new created on date which means that it shows up in by library software on the wrong date.

Thanks again

**Comment by iPzard** [comment]
Thanks for the suggestion! For this though, I think the expected behavior is for newly created files to have a new creation date that represents the date they were actually created. 

However, there are batch scripts available that can help you achieve that, I think [this one](https://gist.github.com/PureOcean/58a802c0cc23441dda108a96152fc9de) in particular would make quick work of what you need.
